### ISSUE TITLE
Produced invalid JSON

### ISSUE THREAD

**Issue by cmacdonald** [chentong0/factoid-wiki#3]
I've fed your model with documents from MSMARCO Document corpus. While the model can't take documents > 512 word pieces (unexpected), more importantly I've also quickly experienced it generating invalid JSON output:

In particular, the model generates, as its 2nd passage, a passed with an extraneous double quote:
`"Grace Saville contributed 61,713 contributions."Science is not just a subject, it's a philosophy for life.",`

Also it hallucinates repeated values of yes (without the quotes) and doesn't terminate the JSON list:
`"Does the Leaning Tower of Pisa really lean?yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes, yes,`

Could you advise please?

You can try my example at
https://colab.research.google.com/drive/1z3YL3evlVczQHWdAfwlJcFGCUCTtmbsP?usp=sharing

**Comment by chentong0** [comment]
I've noticed that you remove the last `</s>` token from strings longer than 512 tokens. I recommend using the tokenizer's truncation feature instead. This will address the issue of repeated values you've mentioned. Consider the following code as an example:
```
input_ids = tokenizer(input_text, return_tensors="pt", max_length=200, truncation=True).input_ids
```

The model is designed for processing passages of approximately 100 words. Therefore, we suggest splitting paragraphs at sentence boundaries, ensuring each segment does not exceed 100 words. This design choice stems from two considerations: (1) the efficiency of breaking down extensive texts like Wikipedia, and (2) the 512-token limit of T5 models. As a result, our training data (https://huggingface.co/datasets/chentong00/propositionizer-wiki-data) uses roughly 100-word paragraphs, which may limit the model's generalizability to significantly longer inputs.
