### ISSUE TITLE
About the quality of GPT-4 generated data

### ISSUE THREAD

**Issue by Hannibal046** [chentong0/factoid-wiki#4]
Hi Teams,
Thanks for this inspiring work!  I am reaching out with a query regarding the data generated by GPT-4. Have you conducted any preliminary experiments to verify the correctness of passage-proposition pairs produced by GPT-4, or to determine the accuracy rate of such data? Your insights on this matter would be greatly appreciated.

Thank you for your time and assistance.

**Comment by chentong0** [comment]
Sorry for the late reply. We only manually reviewed some output from GPT-4 and found it to be satisfactory in the cases we have checked. If you want to verify whether the quality meets your needs, you can check our training data for the propositionizer provided here (https://huggingface.co/datasets/chentong00/propositionizer-wiki-data). 

Additionally, the use of ChatGPT to generate claims/propositions in natural language form has been explored in prior research papers, such as [FactScore](https://aclanthology.org/2023.emnlp-main.741/) (Min et al., 2023) and [WICE](https://aclanthology.org/2023.emnlp-main.470/) (Kamoi et al, 2023). I hope these reference papers will be helpful to you.
